inputs:
  first_name: 'first_name'
  last_name: 'last_name'
  email: 'email'
  phone: 'phone'
  company_name: 'company_name'
  job_title: 'job_title'
  company_type: 'company_type'
  company_size: 'company_size'
  country: 'country'
  province: 'province'
  state: 'state'
  budget: 'budget'
  intention: 'intention'
  form_check: 'form-check_label'
  gdpr_consent: 'gdpr_consent'

errors:
  budget: '//div[@class="invalid-feedback" and contains(text(),"Tell us your annual programmatic budget.")]'
  company_size: '//div[@class="invalid-feedback" and contains(text(),"Tell us the size of your company.")]'
  gdpr_consent: '//div[@class="invalid-feedback" and contains(text(),"Please agree in order for us to process your request.")]'
  intention: '//div[@class="invalid-feedback" and contains(text(),"Tell us how you are looking to work with us.")]'
  first_name: '//div[@class="invalid-feedback" and contains(text(),"Provide your first name.")]'
  last_name: '//div[@class="invalid-feedback" and contains(text(),"Provide your last name.")]'
  email: '//div[@class="invalid-feedback" and contains(text(),"Provide a valid business email.")]'
  phone: '//div[@class="invalid-feedback" and contains(text(),"Provide a phone number with a country code and the + sign.")]'
  company_name: '//div[@class="invalid-feedback" and contains(text(),"Provide the name of the company you work for.")]'
  job_title: '//div[@class="invalid-feedback" and contains(text(),"Provide your job title.")]'
  company_type: '//div[@class="invalid-feedback" and contains(text(),"Tell us the type of company you work for.")]'
  country: '//div[@class="invalid-feedback" and contains(text(),"Tell us what country you are in.")]'
  province: '//div[@class="invalid-feedback" and contains(text(),"Tell us what province you are in.")]'
  state: '//div[@class="invalid-feedback" and contains(text(),"Tell us what state you are in.")]'